CREATE TABLE public.star_planet_data (
    planet_id INT,
    target_id INT,
    kepler_object_Name VARCHAR(50),
    planet_name VARCHAR(100),
    planet_status VARCHAR(50),
    preliminary_status VARCHAR(50),
    confidence_score NUMERIC,
    flag_not_transit_like INT,
    flag_stellar_Eclipse INT,
    flag_centroid_offset INT,
    flag_Ephemeris_match INT,
    orbital_period_days VARCHAR(50),
    orbital_period_upper_err1 NUMERIC,
    orbital_period_lower_err2 NUMERIC,
    tansit_Epoch_time NUMERIC,
    transit_time_upper_err1 NUMERIC,
    transit_time_lower_err2 NUMERIC,
    impact_parameter NUMERIC,
    impact_upper_err1 NUMERIC,
    impact_lower_err2 NUMERIC,
    transit_duration_hours NUMERIC,
    transit_duration_upper_err1 NUMERIC,
    transit_duration_lower_err2 NUMERIC,
    transit_depth_ppm NUMERIC,
    transit_depth_upper_err1 NUMERIC,
    transit_depth_lower_err2 NUMERIC,
    planet_size_earths NUMERIC,
    planet_size_earths_err1 NUMERIC,
    planet_size_earths_err2 NUMERIC,
    planet_temperature_k_elvin INT,
    planet_temperature_k_elvin_err1 NUMERIC,
    planet_temperature_k_elvin_err2 NUMERIC,
    insolation_flux_earths NUMERIC,
    insolation_upper_err1 NUMERIC,
    insolation_lower_err2 NUMERIC,
    signal_to_noise_ratio NUMERIC,
    TEC_planet_number NUMERIC,
    tce_delivery_name VARCHAR(100),
    star_temperature_kelvin INT,  
    star_temperature_kelvin_err1 NUMERIC,
    star_temperature_kelvin_err2 NUMERIC,
    star_gravity_logg NUMERIC,
    star_gravity_upper_err1 NUMERIC,
    star_gravity_lower_err2 NUMERIC,
    star_size_suns NUMERIC,
    star_size_upper_err1 NUMERIC,
    star_size_lower_err2 NUMERIC,
    sky_right_ascension NUMERIC,
    sky_declination NUMERIC,
    kepler_magnitude_brightness NUMERIC
);

UPDATE public.star_planet_data 
SET 
    confidence_score = COALESCE(confidence_score, 0),
    planet_name = COALESCE(planet_name, 'Unknown'),
    TEC_planet_number = COALESCE(TEC_planet_number, 0),
    tce_delivery_name = COALESCE(tce_delivery_name, 'Unknown');


select*from public.star_planet_data ;